### ISSUE TITLE
Wrong version in __version__ variable in init.py V0.4.1

### ISSUE THREAD

**Issue by FernandezMathieu** [vertica/VerticaPy#84] opened 2021-02-09 15:02 UTC
Hello,
The variable __version__ in init.py refer to the wrong version of the product. 

https://github.com/vertica/VerticaPy/blob/0.4.1/verticapy/__init__.py#L49

**Comment by afard** [comment] 2021-02-10 15:18
Hi Fernande

**Comment by afard** [comment] 2021-02-17 16:13
The issue is addressed in version 0.5.0.

**Closed by afard** 2021-02-17 16:13 UTC
