### ISSUE TITLE
Error of join after a group by

### ISSUE THREAD

**Issue by antoinemertz** [vertica/VerticaPy#145] opened 2021-07-07 08:53 UTC
Hello,

I get a problem after making a join of two vDataFrames from one group by on another vDataFrame. I'm working on **VerticaPy 0.6.1** and **Python 3.8.10**.

Here is an reproducible example on the [market dataset](https://www.vertica.com/python/documentation_last/datasets/load_market/). I want to have the top first and second occurences of feature _Form_ for each products in the _Name_ feature:

1. First I group by _Form_ and _Name_ and make a _count_ (`form_by_name`)
2. Secondly I add a vColumn as the row number partition by the _Name_ and order by the _count_
3. Then I extract the top form by product in the `top_form` vDataFrame (`form_by_name.search('rn = 1')`) and the second top form by product (`form_by_name.search('rn = 2')`)
4. Finally I join the two vDataFrames

In the final vDataFrames I have some problems: for a product (here mangoes), I have the good results in the vDataFrames I'm joining but the result is different in the joined vDataFrames. For example for mangoes I'm joining a first top form equal to _'Fresh'_ and a second form equal to _'Dried'_, and in the joined vDataFrame I have first top form and second top form equal to _'Dried'_...

```
>>> from verticapy import *
>>> from verticapy.utilities import *
>>> verticapy.__version__
'0.6.1'
>>> cnxn = vertica_conn(silo)
>>> cursor = cnxn.cursor()
>>> from verticapy.datasets import load_market
>>> market = load_market(cursor = cursor, schema = schema, name = table)
>>> form_by_name = market.groupby(columns = ["Name", "Form"], expr = ["COUNT(*) AS n"])
>>> form_by_name = form_by_name.eval(name = "rn", expr = "ROW_NUMBER() OVER(PARTITION BY Name ORDER BY n DESC)")
>>> top_form = form_by_name.search("rn = 1")
>>> second_form = form_by_name.search("rn = 2")
>>> best_2 = top_form.join(second_form, how="left", on={"Name": "Name"}, expr2=["Name AS Name_2", "Form AS Form_2", "n AS n_2", "rn AS rn_2"])
>>> best_2.search("Form = Form_2").head(1)
        Name     Form    n    rn     Name_2    Form_2    n_2    rn_2  
1    Mangoes    Dried    2     1    Mangoes     Dried      2       2  
Rows: 1-1 | Columns: 8
>>> top_form.search("Name = 'Mangoes'")
        Name     Form    n    rn  
1    Mangoes    Fresh    2     1  
Rows: 1-1 | Columns: 4
>>> second_form.search("Name = 'Mangoes'")
        Name     Form    n    rn  
1    Mangoes    Dried    2     2  
Rows: 1-1 | Columns: 4
>>> market.search("Name = 'Mangoes'")
        Name     Form            Price  
1    Mangoes    Fresh     1.3235173013  
2    Mangoes    Dried    10.1637125484  
3    Mangoes    Fresh    1.37756344703  
4    Mangoes    Dried    8.50464930168  
Rows: 1-4 | Columns: 3
```

If I write intermediate vDataFrame from the group by (`form_by_name`), the problem is solved. I have looked into the SQL request from (`best_2.current_relation()`) I haven't notice any error: I retrieve the SQL requests creating `top_form` and `second_form` and also the correct _group by_ request. But without writing in database, is there a way to have the expected outputs from the join?

Thank you in advance,

**Antoine**

**Comment by oualib** [comment] 2021-07-20 10:27
Hi @antoinemertz, can you please try to reproduce your example on v0.6.3? I am trying your reproducer but in my side, it seems to work.

Thank you,

Badr

**Comment by antoinemertz** [comment] 2021-07-21 16:51
Hi @oualib , thanks for answering.
I have tried on v0.6.3 but still having the same error. Here is a screenshot of my work, it is the same example as mentioned in the first post.

![image](https://user-images.githubusercontent.com/26509655/126527775-3c43e5a8-b3d7-44b4-b51c-b415db536ccc.png)

Is there anything else on hardware or software side which can lead to this situation?

Thanks,

**Antoine**

**Comment by antoinemertz** [comment] 2021-07-30 09:13
Hello @oualib,

I have tested to do it in pure SQL. And the problem remains, so it seems to be a Vertica one and not VerticaPy.

```
>>> from verticapy import *
>>> from verticapy.utilities import *
>>> verticapy.__version__
'0.5.0'
>>> import pandas as pd
>>> cnxn = vertica_conn(silo)
>>> pd.read_sql_query("""
SELECT Name, Form, n, rn, Name_2, Form_2, n_2, rn_2
FROM (
    SELECT x.*, y.Name AS Name_2, y.Form AS Form_2, y.n AS n_2, y.rn AS rn_2
    FROM (
        SELECT *
        FROM (
            SELECT Name, Form, n, rn
            FROM (
                SELECT *
                FROM (
                    SELECT Name, Form, n, ROW_NUMBER() OVER(PARTITION BY Name ORDER BY n DESC) AS rn
                    FROM (
                        SELECT Name, Form, n
                        FROM (
                            SELECT Name, Form, COUNT(*) AS n
                            FROM
                            DTDSWSP310.market GROUP BY Name, Form
                        ) AS GROUPBY1
                    )  AS ROWNUMBER1
                ) AS TEMP1
                WHERE rn = 1
            ) AS TOP1
        ) AS TEMP11
    ) AS x
    LEFT JOIN (
        SELECT *
        FROM (
            SELECT Name, Form, n, rn
            FROM (
                SELECT *
                FROM (
                    SELECT Name, Form, n, ROW_NUMBER() OVER(PARTITION BY Name ORDER BY n DESC) AS rn
                    FROM (
                        SELECT Name, Form, n
                        FROM (
                            SELECT Name, Form, COUNT(*) AS n
                            FROM
                            DTDSWSP310.market GROUP BY Name, Form
                        ) AS GROUPBY2
                    ) AS ROWNUMBER2
                ) AS TEMP2
                WHERE rn = 2
            ) AS TOP2
        ) AS TEMP22
    ) AS y  ON x.Name = y.Name
) AS FINALE
WHERE Form = Form_2
""", cnxn)
                    Name                              Form  n  rn                Name_2                            Form_2  n_2  rn_2
0               Cherries  Canned, packed in syrup or water  2   1              Cherries  Canned, packed in syrup or water    2     2
1             Navy beans                            Canned  2   1            Navy beans                            Canned    2     2
2                Peaches          Packed in syrup or water  2   1               Peaches          Packed in syrup or water    2     2
3                Mangoes                             Dried  2   1               Mangoes                             Dried    2     2
4       Red Kidney Beans                             Dried  2   1      Red Kidney Beans                             Dried    2     2
5                  Plums                    Dried (Prunes)  2   1                 Plums                    Dried (Prunes)    2     2
6            Cauliflower                            Frozen  2   1           Cauliflower                            Frozen    2     2
7           Blackberries                             Fresh  2   1          Blackberries                             Fresh    2     2
8             Lima beans                            Canned  2   1            Lima beans                            Canned    2     2
9       Brussels sprouts                            Frozen  2   1      Brussels sprouts                            Frozen    2     2
10  Great northern beans                            Canned  2   1  Great northern beans                            Canned    2     2
>>>
```

I don't know if you have any contact to see if this problem can be raised to Vertica team directly.

Thank you in advance,

**Antoine**

**Comment by oualib** [comment] 2021-08-01 18:15
@afard can you please look at this issue?

**Comment by afard** [comment] 2021-08-05 20:58
Hi @antoinemertz,

Thanks for your interest in VerticaPy.

The problem here is the approach itself. You should have realized that a virtual DataFrame is a lazy evaluator. That means, it is built based on an underlying SQL statement which is executed only when its result is needed. I see that you have correctly identified the big SQL statement behind the best_2 DataFrame. If you run that query several time, you will realize that you may end up with different results on different runs. To understand why, we should look at the result of your core query where you count the number of distinct pairs of Name, Form.

Let's take a closer look. If we run the following query, we'll find that there the same n for the same Name and different Form.

=> SELECT "Name", "Form", COUNT(*) AS n FROM "public"."market" GROUP BY 1, 2 ORDER BY n DESC, name;
          Name          |            Form            | n
------------------------+----------------------------+---
 "Mixed Vegetables"     | "Frozen"                   | 4
 "Mixed Vegetables"     | "Canned"                   | 4
 "Acorn squash"         | "Fresh"                    | 2
 "Apples"               | "Fresh"                    | 2
 "Apples"               | "Frozen"                   | 2
 "Apples"               | "Ready to drink"           | 2

In other words, any Form of a Name can be rank 1 or 2. Therefore, each time that they are sorted by n to have their row_number assigned, they may appear in a different order. Please note that the [ROW_NUMBER](https://www.vertica.com/docs/10.1.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Analytic/ROW_NUMBERAnalytic.htm) function assigns a sequence of unique numbers to each row in a window partition, starting with 1.

Each time that you query best_2, the subqueries corresponding to top_form and second_form will be executed executed independently. Because of what I explained above, it is quite possible that the same pair of (Name, Form) appear both in top_form and second_form.

If it is fine with your use case to randomly rank items first or second when there is a tie, you can write the result of form_by_name into database so the ranks will be fixed later on.
`>>> form_by_name.to_db("form_by_name", relation_type = "table", inplace = True)`
`>>> top_form = form_by_name.search("rn = 1")`
`>>> second_form = form_by_name.search("rn = 2")`
`>>> best_2 = top_form.join(second_form, how="left", on={"Name": "Name"}, expr2=["Name AS Name_2", "Form AS Form_2", "n AS n_2", "rn AS rn_2"])`

If you look at the main relation of best_2, you'll find out its SQL statement relies on the form_by_name table, so it would generate fixed and meaningful results.
`>>> best_2._VERTICAPY_VARIABLES_['main_relation']
'(SELECT x.*, y.Name AS Name_2, y.Form AS Form_2, y.n AS n_2, y.rn AS rn_2 FROM (SELECT * FROM (SELECT "Name", "Form", "n", "rn" FROM (SELECT * FROM "public"."form_by_name" WHERE rn = 1) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) AS x LEFT JOIN (SELECT * FROM (SELECT "Name", "Form", "n", "rn" FROM (SELECT * FROM "public"."form_by_name" WHERE rn = 2) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) AS y  ON x."Name" = y."Name") VERTICAPY_SUBTABLE'`

**Closed by afard** 2021-08-05 20:58 UTC
Labels: bug

**Comment by antoinemertz** [comment] 2021-08-10 14:58
Hi @afard,

thank for your answer and explanations. To be sure to clearly understand the problem, it is due to the fact that `ROW_NUMBER` function randomly assigns a number to a line if multiple lines in the same group have the same value for `n`, is that correct? So each time I call my vDataFrame, it randomly assigns a new row number to these lines and one line may appear in `top_form` and `second_form` because of that?
And is there a way to set the seed for when computing the `ROW_NUMBER` function to avoid writing the results into database?

Thanks for your help,

**Antoine**

**Comment by afard** [comment] 2021-08-11 03:44
Your understanding is basically correct. Just note that it is not the `ROW_NUMBER` function which is responsible for the random behavior, but Vertica engine in general doesn't guarantee any row order unless it is explicitly sorted by `ORDER BY` clause. The `ROW_NUMBER` function in your case is only ordered by `n`, so the order of rows with the same value of n would be indeterministic.
There is no seed setting, but you can add the Form column to the ORDER BY clause instead of writing to database if it makes sense for your use case.
`form_by_name = form_by_name.eval(name = "rn", expr = "ROW_NUMBER() OVER(PARTITION BY Name ORDER BY n DESC, Form ASC)")`

**Comment by antoinemertz** [comment] 2021-08-18 15:43
Hi @afard,

Thanks for your answer, and good idea, I will do what you mentioned!

Thanks a lot!
