### ISSUE TITLE
Issue to_db function - relation does not exist

### ISSUE THREAD

**Issue by gaetan-dion** [vertica/VerticaPy#346] opened 2022-07-13 15:18 UTC
Hi,

We have a problem of behavior between drop() and to_db() function in VerticaPy 0.8.1.    
  * Python version : 3.8.13   
 
Moreover, to_csv() function has the same error.   

When we want to push our vDataFrame after some transformations to a physical table to persist them, sometimes we meet this error : 
```
ERROR, Message: Relation "schema.table_temp" does not exist, Sqlstate: 42V01, Routine: throwRelationDoesNotExist. 
```    

We tried to use PyODBC (4.0.30) connector instead of vertica_conn as well, to make a test, but we have met the same error :   
```
ProgrammingError: ('42V01', '[42V01] ERROR 4568:  Relation "schema.table" does not exist\n (4568) (SQLExecDirectW)')
```    

We observed that error can happen (sometimes, not always), when we execute successively drop() then to_db() functions.    
We had not this error in VerticaPy 0.5.0.   

The command used is just :   
```python
drop(name="schema.table", cursor=cursor, method='table')
vDf.to_db("schema.table", relation_type="table", inplace=True)
```    

The metadata (current_relation) of one vDataFrame which have this error :   
```sql
'   SELECT',
 '     "col1",',
 '     "col2",',
 '     "Date_reference",',
 '     "categeorie",',
 '     "col3",',
 '     "col4",',
 '     "col5",',
 '     "col6",',
 '     "col7",',
 '     "col8",',
 "     CASE WHEN col4 IN ('11',",
 "     '13',",
 "     '15',",
 "     '17') THEN 'X'                                      WHEN col4 IN ('44',",
 "     '47',",
 "     '49',",
 "     '58',",
 "     '59',",
 '     \'60\') THEN \'Y\' ELSE \'Other\' END AS "X_Y" ',
 '   FROM',
 ' (',
 '   SELECT',
 '     "col1",',
 '     "col2",',
 '     "Date_reference",',
 '     "categeorie",',
 '     "col3",',
 '     "col4",',
 '     "col5",',
 '     "col6",',
 '     "col7",',
 '     "col8" ',
 '   FROM',
 ' (',
 '   SELECT',
 '     x.*,',
 '     y.col4,',
 '     y.col5,',
 '     y.col6,',
 '     y.col7,',
 '     y.col8',
 '   FROM',
 ' "schema"."table_temp" AS x LEFT JOIN "schema"."table_temp_geo" AS y  ON x."col1" = y."col1") ',
 'VERTICAPY_SUBTABLE) ',
 'VERTICAPY_SUBTABLE) ',
 'VERTICAPY_SUBTABLE'
```

**Comment by oualib** [comment] 2022-08-15 16:19
Hi Gaetan,

We tried but we could not reproduce the error, can you please provide a reproducer with one of the default datasets?

Badr

**Comment by oualib** [comment] 2022-10-13 18:28
I will close the issue. Please re-open it if you have a similar issue in a later release.

**Closed by oualib** 2022-10-13 18:28 UTC
Labels: bug
